### ISSUE TITLE
Perhaps this should be part of no-littering?

### ISSUE THREAD

**Issue by shipmints** [meedstrom/eager-state#1]
Nice idea. I have a bunch of independent state savers as many do, some more annoying to set up than others. Same as no-littering, mostly.

Maybe you and Jonas @tarsius could collaborate adding this functionality to https://github.com/emacscollective/no-littering as the scope is pretty similar?

**Comment by tarsius** [comment]
These two packages solve different tasks and should not be merged into one package.

**Comment by shipmints** [comment]
Yep. Perhaps I was too literal. The scope is similar, even if the functions differ.
